config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params["bookmark"]["movie_id"])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.valid?
      @bookmark.save

      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    # using the set_list
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.valid?
      @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    # using the set_list
  end

  def update
    @list.update(list_params)
    redirect_to lists_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class ="form">
  <%= simple_form_for([@list, @bookmark ]) do |f| %>
    <div class="form-title">
      <div class="movie">
      <%= f.association :movie %>
      </div>
      <%= f.label :comment %><br>
      <%= f.text_field :comment%><br><br>
    </div>
    <div class="form-button">
      <%= f.submit %>
  </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <div class ="form">
    <div class="form-total">
      <%= simple_form_for(@list) do |f| %>
      <div class="form-title">
        <%= f.label :name%><br>
        <%= f.text_field :name%><br><br>
      </div>
      <div class="form-picture">
      <%= f.input :photo , as: :file %>
      </div>
      <div class="button btn-primary">
        <%= f.submit "Add", class: "btn btn-primary"%>
      </div>
        <% end %>
      </div>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="form-design">

  <h5>******** Edit your list ********</h5>
  <%= render "form", list: @list %>
</div>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Home</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/80810097?v=4" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="container">
      <div class="list">
      <% @lists.each do |list| %>
        <div class="card-category" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url("<%= cl_image_path list.photo.key%>")'>
          <h4><%= link_to list.name, list_path(list) %></h4>
        </div>
      <% end %>
    </div>
  </div>

app/views/lists/new.html.erb
<div class="form-design">
  <%= render "form", list: @list%>
</div>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Home</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/80810097?v=4" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/lists/new">Create A New List</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class ="container">
  <div class="card-trip">
    <% if @list.photo.attached? %>
      <%= cl_image_tag @list.photo.key, height: 300, width: 400%>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
    <% end %>
      <div class="card-trip-infos">
        <h2><%= @list.name %>'s Bookmarks</h2>
      <div class="options">
        <div class="list-delete">
          <%= link_to "Delete",
            list_path(@list),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
        </div>
          <div class="lis-edit">
            <%= link_to "Edit", edit_list_path(@list) %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-trip-comment">
        <% @list.bookmarks.each do|b|%>
          <div class="card-infos">
            <p><%=b.comment %></p>
            <div class="comment">
              <%= link_to "Delete comment?",
                bookmark_path(b),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
              </div>
            </div>
           <% end %>
          </div>
        </div>